export const STATS = [
  { value: "500+", label: { pt: "Eventos produzidos", en: "Events produced" } },
  { value: "98%",  label: { pt: "Satisfação dos clientes", en: "Client satisfaction" } },
  { value: "25+",  label: { pt: "Anos de experiência", en: "Years of experience" } },
];

export const PROBLEM_POINTS = [
  { k: "01", t: { pt: "Centenas de músicas", en: "Hundreds of songs" },
    d: { pt: "Uma biblioteca infinita e uma única chance de acertar cada momento.", en: "An infinite library, and only one chance to get each moment right." } },
  { k: "02", t: { pt: "Momentos distintos da cerimônia", en: "Distinct ceremony moments" },
    d: { pt: "A entrada, os votos, a assinatura — cada um pede um registro emocional diferente.", en: "The entrance, the vows, the signing — each asks for a different emotional register." } },
  { k: "03", t: { pt: "Expectativas da família", en: "Family expectations" },
    d: { pt: "Tradição, gosto e gerações para conciliar, com elegância.", en: "Tradition, taste and generations to reconcile, gracefully." } },
  { k: "04", t: { pt: "Logística musical", en: "Musical logistics" },
    d: { pt: "Tamanho da orquestra, acústica, transições e deixas — coreografados ao segundo.", en: "Ensemble size, acoustics, transitions and cues — choreographed to the second." } },
];

export const STEPS = [
  { n: "01", t: { pt: "Conte sobre o seu evento", en: "Tell us about your event" },
    d: { pt: "Uma conversa guiada sobre a sua história, o seu espaço e o sentimento que você quer deixar.", en: "A guided conversation about your story, your venue and the feeling you want to leave behind." },
    meta: { pt: "≈ 30 minutos", en: "≈ 30 minutes" } },
  { n: "02", t: { pt: "Receba recomendações curadas", en: "Receive curated recommendations" },
    d: { pt: "Nossos diretores compõem um programa sob medida — repertório, instrumentação e arranjo para cada momento.", en: "Our directors compose a tailored programme — repertoire, instrumentation and arrangement for every moment." },
    meta: { pt: "Em até 5 dias", en: "Within 5 days" } },
  { n: "03", t: { pt: "Aprove a sua trilha final", en: "Approve your final soundtrack" },
    d: { pt: "Refine na nossa plataforma de estúdio até cada deixa ficar perfeita; então produzimos tudo ao vivo.", en: "Refine in our studio platform until every cue is exactly right, then we produce it live." },
    meta: { pt: "Revisões ilimitadas", en: "Unlimited revisions" } },
];

export const TIMELINE = [
  { id: "parents",   label: { pt: "Pais", en: "Parents" },         time: { pt: "Cortejo", en: "Procession" },
    styles: { pt: ["Violoncelo solo", "Neoclássico", "Intimista"], en: ["Solo cello", "Neoclassical", "Intimate"] },
    desc: { pt: "Uma abertura calorosa e firme enquanto as famílias tomam seus lugares — cordas contidas que acalmam o ambiente.", en: "A warm, grounded opening as the families take their place — restrained strings that settle the room." },
    sample: { pt: "Arvo Pärt — Spiegel im Spiegel", en: "Arvo Pärt — Spiegel im Spiegel" } },
  { id: "groomsmen", label: { pt: "Padrinhos", en: "Groomsmen" },  time: { pt: "Cortejo", en: "Procession" },
    styles: { pt: ["Quarteto de cordas", "Moderno", "Cadenciado"], en: ["String quartet", "Modern", "Measured"] },
    desc: { pt: "Uma caminhada confiante e ritmada. Mantemos o pulso firme e a textura limpa.", en: "A confident, rhythmic walk. We keep the pulse steady and the texture clean." },
    sample: { pt: "Pop contemporâneo reimaginado, arranjado para quarteto", en: "Reimagined contemporary pop, arranged for quartet" } },
  { id: "bridegroom", label: { pt: "Noivo", en: "Bridegroom" },    time: { pt: "Entrada", en: "Entrance" },
    styles: { pt: ["Piano e cordas", "Cinematográfico", "Delicado"], en: ["Piano & strings", "Cinematic", "Tender"] },
    desc: { pt: "O primeiro arrebatamento emocional da cerimônia — uma melodia que permanece sem dominar.", en: "The first emotional lift of the ceremony — a melody that lingers without overwhelming." },
    sample: { pt: "Arranjo original, conduzido ao piano", en: "Original arrangement, piano-led" } },
  { id: "children",  label: { pt: "Crianças", en: "Children" },    time: { pt: "Cortejo", en: "Procession" },
    styles: { pt: ["Pizzicato", "Leve", "Lúdico"], en: ["Pizzicato", "Light", "Playful"] },
    desc: { pt: "Um motivo mais leve e brilhante para as crianças — ar e cintilância, nunca açucarado.", en: "A lighter, brighter motif for the flower children — air and sparkle, never saccharine." },
    sample: { pt: "Cordas em pizzicato, acentos de sopros", en: "Pizzicato strings, woodwind accents" } },
  { id: "bride",     label: { pt: "Noiva", en: "Bride" },          time: { pt: "Grande entrada", en: "Grand entrance" },
    styles: { pt: ["Orquestra completa", "Arrebatador", "Icônico"], en: ["Full ensemble", "Soaring", "Iconic"] },
    desc: { pt: "O momento para o qual tudo converge. A orquestra completa chega — comedida, depois luminosa.", en: "The moment everything builds toward. The full ensemble arrives — measured, then luminous." },
    sample: { pt: "Arranjo exclusivo, crescendo de orquestra completa", en: "Bespoke arrangement, full ensemble swell" } },
  { id: "vows",      label: { pt: "Votos", en: "Vows" },           time: { pt: "Cerimônia", en: "Ceremony" },
    styles: { pt: ["Cordas ambientes", "Contido", "Sagrado"], en: ["Ambient strings", "Held back", "Sacred"] },
    desc: { pt: "Música sob as palavras — presente, sem competir. Um acorde sustentado que respira com o ambiente.", en: "Music underneath the words — present, never competing. A held chord that breathes with the room." },
    sample: { pt: "Cordas sustentadas, dinâmica ppp", en: "Sustained strings, ppp dynamic" } },
  { id: "signing",   label: { pt: "Assinatura", en: "Signing" },   time: { pt: "Cerimônia", en: "Ceremony" },
    styles: { pt: ["Violino solo", "Romântico", "Fluido"], en: ["Solo violin", "Romantic", "Flowing"] },
    desc: { pt: "Um interlúdio fluido durante a assinatura — espaço para o ambiente respirar e sorrir.", en: "A flowing interlude as the register is signed — space for the room to exhale and smile." },
    sample: { pt: "Violino solo com leve acompanhamento", en: "Solo violin with light accompaniment" } },
  { id: "exit",      label: { pt: "Saída", en: "Exit" },           time: { pt: "Recessional", en: "Recessional" },
    styles: { pt: ["Metais e cordas", "Triunfal", "Alegre"], en: ["Brass & strings", "Triumphant", "Joyful"] },
    desc: { pt: "Liberdade e celebração. Os metais se juntam às cordas para uma chegada brilhante e inconfundível à alegria.", en: "Release and celebration. Brass joins the strings for a bright, unmistakable arrival into joy." },
    sample: { pt: "Orquestra completa, metais em destaque", en: "Full ensemble, brass-forward" } },
  { id: "reception", label: { pt: "Recepção", en: "Reception" },   time: { pt: "Festa", en: "Celebration" },
    styles: { pt: ["Trio de jazz", "Soul", "Banda ao vivo"], en: ["Jazz trio", "Soul", "Live band"] },
    desc: { pt: "A noite se abre. Fazemos a transição perfeita da orquestra da cerimônia para o programa da festa.", en: "The evening opens up. We transition seamlessly from ceremony ensemble to reception programme." },
    sample: { pt: "Standards de jazz e soul, set de banda ao vivo", en: "Jazz standards & soul, live band set" } },
];

export const PROFILE = {
  couple: "Helena & Marcos",
  date: { pt: "14 de setembro de 2026", en: "14 September 2026" },
  venue: { pt: "Cia. Sinfônica · Salão Ateliê", en: "Cia. Sinfônica · Atelier Hall" },
  formality: 78,
  emotion: {
    pt: { "Intimidade": 86, "Grandiosidade": 64, "Alegria": 72, "Sobriedade": 80 },
    en: { "Intimacy": 86, "Grandeur": 64, "Joy": 72, "Restraint": 80 },
  },
  instrumentation: [
    { id: "strings",  name: { pt: "Cordas", en: "Strings" },      on: true },
    { id: "piano",    name: { pt: "Piano", en: "Piano" },         on: true },
    { id: "voice",    name: { pt: "Voz solo", en: "Solo voice" }, on: true },
    { id: "brass",    name: { pt: "Metais", en: "Brass" },        on: false },
    { id: "woodwind", name: { pt: "Sopros", en: "Woodwind" },     on: true },
    { id: "jazz",     name: { pt: "Trio de jazz", en: "Jazz trio" }, on: false },
  ],
  songs: [
    { title: { pt: "Spiegel im Spiegel", en: "Spiegel im Spiegel" }, artist: { pt: "Arvo Pärt", en: "Arvo Pärt" }, moment: { pt: "Pais", en: "Parents" }, match: 97 },
    { title: { pt: "Arranjo de entrada exclusivo", en: "Bespoke entrance arrangement" }, artist: { pt: "Cia. Sinfônica", en: "Cia. Sinfônica" }, moment: { pt: "Noiva", en: "Bride" }, match: 99 },
    { title: { pt: "Noturno sustentado", en: "Sustained nocturne" }, artist: { pt: "Original", en: "Original" }, moment: { pt: "Votos", en: "Vows" }, match: 94 },
    { title: { pt: "Recessional em Ré", en: "Recessional in D" }, artist: { pt: "Metais e cordas", en: "Brass & strings" }, moment: { pt: "Saída", en: "Exit" }, match: 95 },
  ],
};

export const PACKAGES = [
  { name: { pt: "Essencial", en: "Essential" }, price: { pt: "Solo e duo", en: "Solo & duo" },
    priceNote: { pt: "A partir de R$ 6.800", en: "From R$ 6,800" },
    tagline: { pt: "Para cerimônias intimistas com uma única formação marcante.", en: "For intimate ceremonies with a single defining ensemble." },
    feat: { pt: ["Consultoria de descoberta", "Programa curado para a cerimônia", "Formação solo ou duo", "Uma rodada de revisão", "Apresentação ao vivo na cerimônia"],
            en: ["Discovery consultation", "Curated programme for the ceremony", "Solo or duo ensemble", "One revision round", "Live performance, ceremony"] },
    featured: false },
  { name: { pt: "Premium", en: "Premium" }, price: { pt: "Cerimônia completa", en: "Full ceremony" },
    priceNote: { pt: "A partir de R$ 14.500", en: "From R$ 14,500" },
    tagline: { pt: "Nossa experiência mais escolhida — cada momento da cerimônia, totalmente musicado.", en: "Our most chosen experience — every ceremony moment, fully scored." },
    feat: { pt: ["Tudo do Essencial", "De quarteto a pequena orquestra", "Acesso ao motor de personalização", "Revisões ilimitadas", "Arranjo de entrada exclusivo", "Direção de som no local", "Cerimônia + coquetel"],
            en: ["Everything in Essential", "Quartet to small ensemble", "Personalization engine access", "Unlimited revisions", "Bespoke entrance arrangement", "On-site sound direction", "Ceremony + cocktail hour"] },
    featured: true },
  { name: { pt: "Experiência Completa", en: "Full Experience" }, price: { pt: "Da cerimônia à noite", en: "Ceremony → night" },
    priceNote: { pt: "Sob proposta", en: "By proposal" },
    tagline: { pt: "A produção completa — do primeiro cortejo à última dança.", en: "The complete production — from the first procession to the last dance." },
    feat: { pt: ["Tudo do Premium", "Orquestra completa + banda da festa", "Diretor musical dedicado", "Opção de composição original", "Ensaio dos momentos-chave", "Produção da noite inteira"],
            en: ["Everything in Premium", "Full ensemble + reception band", "Dedicated music director", "Original composition option", "Rehearsal with key moments", "Full-evening production"] },
    featured: false },
];

export const TESTIMONIALS = [
  { quote: { pt: "Eles não escolheram músicas — entenderam o sentimento do nosso dia e construíram o som ao redor dele. Todos os convidados comentaram a música.", en: "They didn't choose songs — they understood the feeling of our day and built the sound around it. Every guest mentioned the music." },
    name: "Helena & Marcos", meta: { pt: "Cerimônia · São Paulo", en: "Ceremony · São Paulo" }, initials: "HM", rating: 5, moment: { pt: "Experiência Completa", en: "Full Experience" } },
  { quote: { pt: "O arranjo de entrada foi escrito para nós. Quando a orquestra cresceu, minha mãe chorou antes mesmo de eu chegar ao altar.", en: "The entrance arrangement was written for us. When the ensemble swelled, my mother cried before I even reached the aisle." },
    name: "Beatriz & Tomás", meta: { pt: "Cerimônia ao ar livre · Campinas", en: "Garden ceremony · Campinas" }, initials: "BT", rating: 5, moment: { pt: "Premium", en: "Premium" } },
  { quote: { pt: "Precisão é a palavra. Cada deixa caiu no segundo certo e, ainda assim, nunca pareceu mecânico — pareceu profundamente humano.", en: "Precision is the word. Every cue landed to the second, and yet it never felt mechanical — it felt deeply human." },
    name: "Carolina & André", meta: { pt: "Salão Ateliê", en: "Atelier Hall" }, initials: "CA", rating: 5, moment: { pt: "Premium", en: "Premium" } },
  { quote: { pt: "Estávamos perdidos em meio às escolhas até a primeira consultoria. Eles transformaram centenas de opções em um único programa perfeito.", en: "We were overwhelmed by choices until the first consultation. They turned hundreds of options into one perfect programme." },
    name: "Júlia & Rafael", meta: { pt: "Vinícola", en: "Vineyard estate" }, initials: "JR", rating: 5, moment: { pt: "Experiência Completa", en: "Full Experience" } },
  { quote: { pt: "A experiência de fornecedor mais elegante de todo o casamento. Calmos, confiantes e silenciosamente brilhantes do início ao fim.", en: "The most elegant vendor experience of the entire wedding. Calm, confident, and quietly brilliant from start to finish." },
    name: "Marina & Pedro", meta: { pt: "Cerimônia litorânea", en: "Coastal ceremony" }, initials: "MP", rating: 5, moment: { pt: "Premium", en: "Premium" } },
];

export const TESTI_COLUMNS = [
  { initials: "HM", name: "Helena & Marcos", role: { pt: "Cerimônia · São Paulo", en: "Ceremony · São Paulo" },
    text: { pt: "Entenderam o sentimento do nosso dia e construíram o som ao redor dele. Todos os convidados comentaram a música.", en: "They understood the feeling of our day and built the sound around it. Every guest mentioned the music." } },
  { initials: "BT", name: "Beatriz & Tomás", role: { pt: "Ao ar livre · Campinas", en: "Garden · Campinas" },
    text: { pt: "O arranjo de entrada foi escrito para nós. Quando a orquestra cresceu, minha mãe chorou antes do altar.", en: "The entrance arrangement was written for us. When the ensemble swelled, my mother cried before the aisle." } },
  { initials: "CA", name: "Carolina & André", role: { pt: "Salão Ateliê", en: "Atelier Hall" },
    text: { pt: "Cada deixa caiu no segundo certo e, ainda assim, nunca pareceu mecânico — pareceu profundamente humano.", en: "Every cue landed to the second, and yet it never felt mechanical — it felt deeply human." } },
  { initials: "JR", name: "Júlia & Rafael", role: { pt: "Vinícola", en: "Vineyard estate" },
    text: { pt: "Transformaram centenas de opções em um único programa perfeito. Estávamos perdidos até a primeira consultoria.", en: "They turned hundreds of options into one perfect programme. We were lost until the first consultation." } },
  { initials: "MP", name: "Marina & Pedro", role: { pt: "Cerimônia litorânea", en: "Coastal ceremony" },
    text: { pt: "A experiência de fornecedor mais elegante de todo o casamento. Calmos, confiantes e silenciosamente brilhantes.", en: "The most elegant vendor experience of the wedding. Calm, confident and quietly brilliant." } },
  { initials: "LF", name: "Larissa & Felipe", role: { pt: "Capela · Itu", en: "Chapel · Itu" },
    text: { pt: "A trilha da cerimônia parecia inevitável, como se nenhuma outra música pudesse existir naquele momento.", en: "The ceremony's soundtrack felt inevitable, as if no other music could have existed in that moment." } },
  { initials: "GC", name: "Gabriela & Caio", role: { pt: "Fazenda · Sorocaba", en: "Estate · Sorocaba" },
    text: { pt: "Profissionalismo absoluto. Os ensaios anteciparam cada transição — no dia, tudo fluiu sem um único tropeço.", en: "Absolute professionalism. The rehearsals anticipated every transition — on the day, everything flowed flawlessly." } },
  { initials: "VR", name: "Vitória & Rodrigo", role: { pt: "Hotel · São Paulo", en: "Hotel · São Paulo" },
    text: { pt: "O coquetel virou um show de jazz íntimo. Os convidados ficaram dançando muito além do esperado.", en: "The cocktail hour turned into an intimate jazz set. Guests danced far longer than we ever expected." } },
  { initials: "IN", name: "Isabela & Nicolas", role: { pt: "Igreja · Campos do Jordão", en: "Church · Campos do Jordão" },
    text: { pt: "Cordas sob os votos, metais na saída. A curva emocional foi desenhada com uma precisão que ainda me emociona.", en: "Strings under the vows, brass at the exit. The emotional arc was designed with a precision that still moves me." } },
];
