import type { Question } from "../../../types/quiz.types.js";

export const block5Questions: Question[] = [
  {
    id: "B5_ENTRANCE",
    block: 5,
    question: "A entrada da noiva/festejado deve ser:",
    type: "single_choice",
    trigger: { field: "B0Q1", includes: ["wedding", "civil_wedding", "birthday_15"] },
    options: [
      { value: "classic_romantic", label: "Clássica e romântica — algo que faça chorar de emoção" },
      { value: "modern_pop",       label: "Moderna e pop — uma música com significado especial para nós" },
      { value: "cinematic",        label: "Cinematográfica — como uma cena de filme" },
      { value: "surprising",       label: "Surpreendente — algo que ninguém espera" },
      { value: "religious",        label: "Religiosa / Litúrgica" },
      { value: "custom",           label: "Já tenho uma música específica em mente" },
    ],
  },
  {
    id: "B5_FIRST_DANCE",
    block: 5,
    question: "O primeiro dance / valsa deve ter qual clima?",
    type: "single_choice",
    trigger: { field: "B0Q1", includes: ["wedding", "civil_wedding", "birthday_15"] },
    options: [
      { value: "intimate_slow",   label: "Lento e íntimo — só nós dois no mundo" },
      { value: "joyful_dance",    label: "Alegre e dançante — queremos animar a festa com o dance" },
      { value: "emotional_ballad",label: "Emocionante — uma balada que nos representa" },
      { value: "classic_waltz",   label: "Valsa clássica / formal" },
      { value: "no_first_dance",  label: "Não teremos este momento" },
    ],
  },
  {
    id: "B5_COCKTAIL",
    block: 5,
    question: "Durante o coquetel / chegada dos convidados, a música deve ser:",
    type: "single_choice",
    options: [
      { value: "lounge_jazz",      label: "Lounge / Jazz — sofisticada e relaxante" },
      { value: "mpb_acoustic",     label: "MPB acústica — acolhedora e brasileira" },
      { value: "bossa_nova",       label: "Bossa Nova — elegante e contemporânea" },
      { value: "light_pop",        label: "Pop leve — familiar e agradável" },
      { value: "classical_strings",label: "Clássica — quarteto de cordas ou piano" },
      { value: "upbeat",           label: "Animada — já no ritmo de festa desde o início" },
    ],
  },
  {
    id: "B5_DINNER",
    block: 5,
    question: "Durante o jantar, a trilha deve ser:",
    type: "single_choice",
    options: [
      { value: "soft_background",  label: "Suave de fundo — não deve atrapalhar as conversas" },
      { value: "meaningful",       label: "Significativa — músicas que escolhemos com cuidado" },
      { value: "jazz_bossa",       label: "Jazz / Bossa — elegante e intemporal" },
      { value: "themed",           label: "Com tema — ex: músicas de viagens, décadas específicas" },
      { value: "same_as_party",    label: "Já no ritmo da festa" },
    ],
  },
  {
    id: "B5_PARTY",
    block: 5,
    question: "O pico da festa deve ser:",
    type: "multi_choice",
    maxSelections: 3,
    options: [
      { value: "hit_parade",          label: "Hits do momento — o que toca nas rádios" },
      { value: "throwback",           label: "Flashback — hits dos anos 80, 90 e 2000" },
      { value: "brazilian_party",     label: "Pagode, samba, axé — festa brasileira pura" },
      { value: "sertanejo_univ",      label: "Sertanejo universitário / romântico" },
      { value: "electronic_dance",    label: "Eletrônica / house — dança intensa" },
      { value: "international_pop",   label: "Pop internacional — clássicos do mundo" },
      { value: "forro_nordestino",    label: "Forró / música nordestina" },
      { value: "rock_classics",       label: "Rock clássico / hard rock" },
    ],
  },
  {
    id: "B5_CLOSING",
    block: 5,
    question: "Como você quer encerrar o evento?",
    type: "single_choice",
    options: [
      { value: "emotional_ballad",   label: "Com uma balada emocionante — terminar com lágrimas de alegria" },
      { value: "high_energy",        label: "No pico de energia — última música explodindo a pista" },
      { value: "meaningful_song",    label: "Com uma música com significado especial — como um mantra" },
      { value: "sentimental_classic",label: "Com um clássico sentimental — todos cantando juntos" },
      { value: "religious_closing",  label: "Com uma música religiosa / de bênção" },
    ],
  },
];
