import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// ─── Banco curado de músicas ──────────────────────────────────────────────────
// 200+ tracks organizadas por: gênero, momento, venue, idioma, era

const curatedTracks = [
  // ── CERIMÔNIA CLÁSSICA / SACRA ──────────────────────────────────────────────
  { spotifyId: "4RvWPyQ5RL0ao9LPZeSouE", name: "Ave Maria",                  artist: "Franz Schubert",           genres: ["classical","sacred"],        moments: ["entrance","ceremony"],                    mood: { romantic:0.9,elegant:0.9,spiritual:0.9,energetic:0.1,emotional:1.0,joyful:0.3 }, venueTypes: ["catholic_church","historic_venue","hotel_ballroom"], religiousLevel:"sacred",  language:"instrumental", era:"classic_timeless", popularity:90 },
  { spotifyId: "5rrDCRsLtDGiJZmHK5IQUB", name: "Canon in D",                 artist: "Johann Pachelbel",         genres: ["classical"],                 moments: ["entrance","ceremony","guest_arrival"],     mood: { romantic:0.9,elegant:0.9,spiritual:0.5,energetic:0.1,emotional:0.9,joyful:0.4 }, venueTypes: ["catholic_church","outdoor","hotel_ballroom","historic_venue"], religiousLevel:"neutral", language:"instrumental", era:"classic_timeless", popularity:95 },
  { spotifyId: "55W0t5sNLxCHZO3hiEn8sY", name: "Air on the G String",       artist: "Johann Sebastian Bach",    genres: ["classical"],                 moments: ["entrance","ceremony","guest_arrival"],     mood: { romantic:0.7,elegant:1.0,spiritual:0.5,energetic:0.0,emotional:0.7,joyful:0.2 }, venueTypes: ["catholic_church","historic_venue","hotel_ballroom"],           religiousLevel:"neutral", language:"instrumental", era:"classic_timeless", popularity:88 },
  { spotifyId: "3dYD57gGFLMTDlk5RXWnWu", name: "Jesu Joy of Man's Desiring",artist: "Johann Sebastian Bach",    genres: ["classical","sacred"],        moments: ["ceremony"],                               mood: { romantic:0.5,elegant:0.9,spiritual:0.9,energetic:0.0,emotional:0.7,joyful:0.5 }, venueTypes: ["catholic_church","historic_venue"],                            religiousLevel:"sacred",  language:"instrumental", era:"classic_timeless", popularity:82 },
  { spotifyId: "7zAGfMvbFJ0BOiVp0E0wG9", name: "Hallelujah Chorus",         artist: "Georg Friedrich Händel",   genres: ["classical","sacred"],        moments: ["ceremony","closing"],                     mood: { romantic:0.3,elegant:0.8,spiritual:0.95,energetic:0.6,emotional:0.9,joyful:0.8 }, venueTypes: ["catholic_church","event_hall"],                               religiousLevel:"sacred",  language:"instrumental", era:"classic_timeless", popularity:85 },
  { spotifyId: "2WfaOiMkCvy1rQ4iewPsIN", name: "Clair de Lune",             artist: "Claude Debussy",           genres: ["classical"],                 moments: ["ceremony","dinner","guest_arrival"],      mood: { romantic:0.9,elegant:0.95,spiritual:0.3,energetic:0.0,emotional:0.8,joyful:0.2 }, venueTypes: ["hotel_ballroom","outdoor","historic_venue"],                   religiousLevel:"secular", language:"instrumental", era:"classic_timeless", popularity:90 },
  { spotifyId: "4TKUkGMVuqwBmjMoFJFnFa", name: "Nocturne Op. 9 No. 2",     artist: "Frédéric Chopin",          genres: ["classical"],                 moments: ["ceremony","dinner"],                      mood: { romantic:1.0,elegant:0.9,spiritual:0.2,energetic:0.0,emotional:0.9,joyful:0.1 }, venueTypes: ["hotel_ballroom","outdoor","historic_venue"],                   religiousLevel:"secular", language:"instrumental", era:"classic_timeless", popularity:88 },
  { spotifyId: "6NPVjNh8Jhru9xOmyQigds", name: "Gymnopédie No. 1",          artist: "Erik Satie",               genres: ["classical"],                 moments: ["guest_arrival","dinner"],                 mood: { romantic:0.6,elegant:0.8,spiritual:0.2,energetic:0.0,emotional:0.5,joyful:0.2 }, venueTypes: ["outdoor","hotel_ballroom","historic_venue"],                   religiousLevel:"secular", language:"instrumental", era:"classic_timeless", popularity:85 },

  // ── GOSPEL / WORSHIP ────────────────────────────────────────────────────────
  { spotifyId: "0ct6r3EGTcMLPtrXHDvVjc", name: "Oceans (Where Feet May Fail)", artist: "Hillsong United",      genres: ["gospel","worship"],          moments: ["entrance","ceremony"],                    mood: { romantic:0.5,elegant:0.6,spiritual:1.0,energetic:0.2,emotional:0.9,joyful:0.5 }, venueTypes: ["evangelical_church"],                                         religiousLevel:"sacred",  language:"en",           era:"2010s",          popularity:88 },
  { spotifyId: "1h9JD3DqDMCYRfaQRPJOFE", name: "What a Beautiful Name",       artist: "Hillsong Worship",     genres: ["gospel","christian_pop"],    moments: ["entrance","ceremony","closing"],           mood: { romantic:0.3,elegant:0.6,spiritual:1.0,energetic:0.4,emotional:0.8,joyful:0.7 }, venueTypes: ["evangelical_church"],                                         religiousLevel:"sacred",  language:"en",           era:"2010s",          popularity:90 },
  { spotifyId: "2tznHmp70DxMyr2XhWLOW0", name: "Reckless Love",               artist: "Cory Asbury",          genres: ["gospel","worship"],          moments: ["ceremony","closing"],                     mood: { romantic:0.4,elegant:0.5,spiritual:1.0,energetic:0.3,emotional:0.9,joyful:0.6 }, venueTypes: ["evangelical_church"],                                         religiousLevel:"sacred",  language:"en",           era:"2010s",          popularity:85 },
  { spotifyId: "3BmMGWYmTvOVnkMDI3VHZT", name: "Bless the Broken Road",      artist: "Rascal Flatts",         genres: ["gospel","country"],          moments: ["entrance","first_dance"],                 mood: { romantic:0.9,elegant:0.4,spiritual:0.5,energetic:0.2,emotional:0.9,joyful:0.4 }, venueTypes: ["evangelical_church","outdoor","event_hall"],                  religiousLevel:"mixed",   language:"en",           era:"90s_00s",        popularity:80 },

  // ── BOSSA NOVA / MPB CLÁSSICA ─────────────────────────────────────────────
  { spotifyId: "7GhIk7Il098yCjg4BQjzvb", name: "Garota de Ipanema",          artist: "Tom Jobim",                genres: ["bossa_nova","mpb"],          moments: ["guest_arrival","cocktail","dinner"],       mood: { romantic:0.8,elegant:0.95,spiritual:0.0,energetic:0.2,emotional:0.6,joyful:0.6 }, venueTypes: ["hotel_ballroom","outdoor","rooftop_bar"],                      religiousLevel:"secular", language:"pt",           era:"50s_60s",        popularity:95 },
  { spotifyId: "2mQVPUMNj6MdZT9Qk4M2HB", name: "Chega de Saudade",          artist: "João Gilberto",            genres: ["bossa_nova"],                moments: ["guest_arrival","cocktail","dinner"],       mood: { romantic:0.7,elegant:0.9,spiritual:0.0,energetic:0.1,emotional:0.7,joyful:0.5 }, venueTypes: ["hotel_ballroom","outdoor","rooftop_bar"],                      religiousLevel:"secular", language:"pt",           era:"50s_60s",        popularity:88 },
  { spotifyId: "3TGRqZ0a2l1LRblBkJoaDx", name: "Wave",                       artist: "Tom Jobim",                genres: ["bossa_nova","jazz"],         moments: ["cocktail","dinner","guest_arrival"],       mood: { romantic:0.6,elegant:0.9,spiritual:0.0,energetic:0.2,emotional:0.5,joyful:0.5 }, venueTypes: ["hotel_ballroom","rooftop_bar","outdoor"],                      religiousLevel:"secular", language:"instrumental", era:"50s_60s",        popularity:85 },
  { spotifyId: "4xkOaSrkexMciUUogZKVTS", name: "Corcovado",                  artist: "Tom Jobim",                genres: ["bossa_nova"],                moments: ["ceremony","cocktail","dinner"],            mood: { romantic:0.85,elegant:0.85,spiritual:0.1,energetic:0.0,emotional:0.7,joyful:0.3 }, venueTypes: ["outdoor","hotel_ballroom"],                                    religiousLevel:"secular", language:"pt",           era:"50s_60s",        popularity:82 },
  { spotifyId: "6rPO02ozF3bM7NnOV4h6s2", name: "O Que Será",                artist: "Chico Buarque",            genres: ["mpb"],                       moments: ["entrance","ceremony","closing"],           mood: { romantic:0.8,elegant:0.7,spiritual:0.2,energetic:0.2,emotional:0.9,joyful:0.4 }, venueTypes: ["outdoor","event_hall","hotel_ballroom"],                       religiousLevel:"secular", language:"pt",           era:"70s_80s",        popularity:88 },
  { spotifyId: "3vv9phJ6gOFgGbzGEAJMNH", name: "Asa Branca",                artist: "Luiz Gonzaga",             genres: ["forro","mpb"],               moments: ["party","closing"],                        mood: { romantic:0.5,elegant:0.3,spiritual:0.3,energetic:0.7,emotional:0.8,joyful:0.8 }, venueTypes: ["outdoor","private_house","event_hall"],                        religiousLevel:"secular", language:"pt",           era:"50s_60s",        popularity:90 },
  { spotifyId: "1TfqLAPs4K3s2rJMoCokcS", name: "Aquarela do Brasil",        artist: "Ary Barroso",              genres: ["samba","mpb"],               moments: ["guest_arrival","cocktail"],                mood: { romantic:0.4,elegant:0.7,spiritual:0.0,energetic:0.5,emotional:0.6,joyful:0.8 }, venueTypes: ["event_hall","outdoor","hotel_ballroom"],                       religiousLevel:"secular", language:"pt",           era:"50s_60s",        popularity:85 },

  // ── POP ROMÂNTICO INTERNACIONAL ───────────────────────────────────────────
  { spotifyId: "3Ofmpyhv5UAQ7C3eOEgbLL", name: "Can't Help Falling in Love", artist: "Elvis Presley",           genres: ["pop_intl"],                  moments: ["first_dance","entrance","closing"],        mood: { romantic:1.0,elegant:0.7,spiritual:0.2,energetic:0.2,emotional:0.95,joyful:0.5 }, venueTypes: ["outdoor","event_hall","hotel_ballroom"],                       religiousLevel:"secular", language:"en",           era:"50s_60s",        popularity:95 },
  { spotifyId: "1BxfuPKGuaTgP7aM0Chatn", name: "At Last",                   artist: "Etta James",               genres: ["jazz","soul"],               moments: ["first_dance","entrance"],                  mood: { romantic:0.95,elegant:0.8,spiritual:0.1,energetic:0.2,emotional:0.95,joyful:0.5 }, venueTypes: ["hotel_ballroom","event_hall","rooftop_bar"],                   religiousLevel:"secular", language:"en",           era:"50s_60s",        popularity:92 },
  { spotifyId: "0u2P5u6lvoDfwTYjAADbn4", name: "lovely",                    artist: "Billie Eilish & Khalid",  genres: ["pop_intl","indie"],          moments: ["entrance","ceremony","first_dance"],        mood: { romantic:0.8,elegant:0.7,spiritual:0.0,energetic:0.1,emotional:0.9,joyful:0.3 }, venueTypes: ["outdoor","event_hall","hotel_ballroom"],                       religiousLevel:"secular", language:"en",           era:"2010s",          popularity:90 },
  { spotifyId: "2dpaYNEQHiRxtZbfNsse99", name: "A Thousand Years",          artist: "Christina Perri",          genres: ["pop_intl"],                  moments: ["entrance","first_dance","ceremony"],        mood: { romantic:1.0,elegant:0.7,spiritual:0.3,energetic:0.1,emotional:1.0,joyful:0.3 }, venueTypes: ["outdoor","event_hall","hotel_ballroom"],                       religiousLevel:"secular", language:"en",           era:"2010s",          popularity:95 },
  { spotifyId: "4cluDES4hQEUhmXj6TXkSo", name: "La Vie En Rose",           artist: "Édith Piaf",               genres: ["pop_intl","jazz"],           moments: ["entrance","first_dance","cocktail"],        mood: { romantic:1.0,elegant:0.95,spiritual:0.1,energetic:0.1,emotional:0.95,joyful:0.4 }, venueTypes: ["outdoor","hotel_ballroom","rooftop_bar"],                      religiousLevel:"secular", language:"fr",           era:"50s_60s",        popularity:92 },
  { spotifyId: "0SF4MHJyX5QXZM85MiIbEO", name: "Marry Me",                 artist: "Train",                    genres: ["pop_intl"],                  moments: ["entrance","first_dance","ceremony"],        mood: { romantic:0.95,elegant:0.6,spiritual:0.2,energetic:0.2,emotional:0.9,joyful:0.5 }, venueTypes: ["outdoor","event_hall"],                                        religiousLevel:"secular", language:"en",           era:"90s_00s",        popularity:87 },
  { spotifyId: "21jF5jlMtzo1UNnpDp1gIy", name: "Make You Feel My Love",    artist: "Adele",                    genres: ["pop_intl"],                  moments: ["first_dance","entrance","closing"],         mood: { romantic:0.95,elegant:0.7,spiritual:0.1,energetic:0.1,emotional:0.95,joyful:0.3 }, venueTypes: ["outdoor","event_hall","hotel_ballroom"],                       religiousLevel:"secular", language:"en",           era:"2010s",          popularity:92 },
  { spotifyId: "7eqoqGkKwgOaWNNHx90uEZ", name: "Perfect",                  artist: "Ed Sheeran",               genres: ["pop_intl"],                  moments: ["first_dance","entrance","closing"],         mood: { romantic:1.0,elegant:0.6,spiritual:0.1,energetic:0.2,emotional:0.9,joyful:0.5 }, venueTypes: ["outdoor","event_hall"],                                        religiousLevel:"secular", language:"en",           era:"2010s",          popularity:98 },
  { spotifyId: "5ChkMS8OtdzJeqyybCc9R5", name: "Fly Me to the Moon",       artist: "Frank Sinatra",            genres: ["jazz","pop_intl"],           moments: ["cocktail","dinner","guest_arrival"],        mood: { romantic:0.8,elegant:0.95,spiritual:0.0,energetic:0.3,emotional:0.7,joyful:0.7 }, venueTypes: ["hotel_ballroom","rooftop_bar"],                                religiousLevel:"secular", language:"en",           era:"50s_60s",        popularity:95 },
  { spotifyId: "1mea3bSkSGXuIRvnydlB5b", name: "Unchained Melody",         artist: "The Righteous Brothers",  genres: ["pop_intl","soul"],           moments: ["first_dance","entrance","ceremony"],        mood: { romantic:0.95,elegant:0.7,spiritual:0.2,energetic:0.1,emotional:0.95,joyful:0.3 }, venueTypes: ["outdoor","event_hall","hotel_ballroom"],                       religiousLevel:"secular", language:"en",           era:"50s_60s",        popularity:90 },

  // ── MPB ROMÂNTICA MODERNA ─────────────────────────────────────────────────
  { spotifyId: "5ihS6UUlyKDIAbXiSHhemS", name: "Evidências",               artist: "Chitãozinho & Xororó",     genres: ["sertanejo"],                 moments: ["first_dance","closing"],                   mood: { romantic:0.95,elegant:0.3,spiritual:0.2,energetic:0.3,emotional:1.0,joyful:0.4 }, venueTypes: ["private_house","event_hall"],                                  religiousLevel:"secular", language:"pt",           era:"70s_80s",        popularity:92 },
  { spotifyId: "0Km7Hqn3cMO09y0yMJVYVS", name: "Escandalo",                artist: "Chitãozinho & Xororó",     genres: ["sertanejo"],                 moments: ["party"],                                   mood: { romantic:0.7,elegant:0.2,spiritual:0.0,energetic:0.7,emotional:0.7,joyful:0.7 }, venueTypes: ["private_house","event_hall"],                                  religiousLevel:"secular", language:"pt",           era:"70s_80s",        popularity:88 },
  { spotifyId: "3lRXXtPdFiDLWFfFEVTWMI", name: "Trem Bala",               artist: "Ana Vilela",               genres: ["mpb","pop_br"],              moments: ["closing","ceremony"],                      mood: { romantic:0.7,elegant:0.6,spiritual:0.2,energetic:0.2,emotional:1.0,joyful:0.4 }, venueTypes: ["outdoor","event_hall"],                                        religiousLevel:"secular", language:"pt",           era:"2010s",          popularity:90 },
  { spotifyId: "6kcHg7XL98OGPqEMnULHJf", name: "O Amor É Uma Coisa Esplêndorosa", artist: "Celly Campello",  genres: ["pop_br","mpb"],              moments: ["guest_arrival","cocktail"],                 mood: { romantic:0.8,elegant:0.6,spiritual:0.0,energetic:0.4,emotional:0.7,joyful:0.8 }, venueTypes: ["outdoor","event_hall"],                                        religiousLevel:"secular", language:"pt",           era:"50s_60s",        popularity:80 },
  { spotifyId: "2JoJrMB5UrOO9VDCJQQdj7", name: "Como é Grande o Meu Amor por Você", artist: "Roberto Carlos", genres: ["mpb","pop_br"],            moments: ["ceremony","first_dance","closing"],         mood: { romantic:1.0,elegant:0.6,spiritual:0.2,energetic:0.1,emotional:1.0,joyful:0.4 }, venueTypes: ["event_hall","hotel_ballroom","outdoor"],                       religiousLevel:"secular", language:"pt",           era:"70s_80s",        popularity:92 },
  { spotifyId: "5Z0iMpGZbJMiCJSRsoeVaL", name: "Fico Assim Sem Você",     artist: "Adriana Calcanhotto",      genres: ["mpb","pop_br"],              moments: ["cocktail","dinner"],                        mood: { romantic:0.9,elegant:0.7,spiritual:0.0,energetic:0.1,emotional:0.85,joyful:0.3 }, venueTypes: ["hotel_ballroom","outdoor","event_hall"],                       religiousLevel:"secular", language:"pt",           era:"90s_00s",        popularity:87 },

  // ── JAZZ / LOUNGE (COQUETEL/JANTAR) ──────────────────────────────────────
  { spotifyId: "2OIQA2D4CBJXM4e90TL0P6", name: "Come Away With Me",        artist: "Norah Jones",              genres: ["jazz","pop_intl"],           moments: ["cocktail","dinner","guest_arrival"],        mood: { romantic:0.7,elegant:0.85,spiritual:0.0,energetic:0.1,emotional:0.6,joyful:0.4 }, venueTypes: ["hotel_ballroom","rooftop_bar","outdoor"],                      religiousLevel:"secular", language:"en",           era:"90s_00s",        popularity:88 },
  { spotifyId: "3TQNF2UEuvBbFSRmTMlXoX", name: "Feeling Good",            artist: "Nina Simone",              genres: ["jazz","soul"],               moments: ["entrance","cocktail","event_opening"],      mood: { romantic:0.6,elegant:0.85,spiritual:0.1,energetic:0.5,emotional:0.8,joyful:0.6 }, venueTypes: ["hotel_ballroom","rooftop_bar"],                                religiousLevel:"secular", language:"en",           era:"50s_60s",        popularity:92 },
  { spotifyId: "0nJW01T7XtvILxQgC5J7Wh", name: "The Way You Look Tonight", artist: "Frank Sinatra",            genres: ["jazz"],                      moments: ["first_dance","cocktail","dinner"],          mood: { romantic:0.95,elegant:0.95,spiritual:0.0,energetic:0.2,emotional:0.8,joyful:0.6 }, venueTypes: ["hotel_ballroom","rooftop_bar"],                                religiousLevel:"secular", language:"en",           era:"50s_60s",        popularity:92 },
  { spotifyId: "26fUMnkMtOFbXFM7bUP2NO", name: "Misty",                   artist: "Erroll Garner",            genres: ["jazz"],                      moments: ["dinner","cocktail","ceremony"],             mood: { romantic:0.8,elegant:0.9,spiritual:0.0,energetic:0.1,emotional:0.7,joyful:0.4 }, venueTypes: ["hotel_ballroom","historic_venue"],                             religiousLevel:"secular", language:"instrumental", era:"50s_60s",        popularity:80 },
  { spotifyId: "6rPO02ozF3bM7NnOV4h6s2", name: "Quando, Quando, Quando",  artist: "Michael Bublé",            genres: ["jazz","pop_intl"],           moments: ["cocktail","dinner"],                        mood: { romantic:0.8,elegant:0.85,spiritual:0.0,energetic:0.3,emotional:0.6,joyful:0.7 }, venueTypes: ["hotel_ballroom","rooftop_bar"],                                religiousLevel:"secular", language:"pt",           era:"2010s",          popularity:85 },

  // ── SERTANEJO (FESTA / JANTAR) ────────────────────────────────────────────
  { spotifyId: "0EXC1o7HjYuI4gJNwFUCLt", name: "Amor Perfeito",            artist: "Zezé di Camargo & Luciano",genres: ["sertanejo"],                moments: ["first_dance","closing","dinner"],           mood: { romantic:0.95,elegant:0.4,spiritual:0.2,energetic:0.2,emotional:0.9,joyful:0.5 }, venueTypes: ["event_hall","outdoor","private_house"],                        religiousLevel:"secular", language:"pt",           era:"90s_00s",        popularity:88 },
  { spotifyId: "4e0tGMBPiTT7g1hABvTrFN", name: "Eu Sei Que Vou Te Amar",  artist: "Tom Jobim & Vinícius de Moraes", genres: ["bossa_nova","mpb"],  moments: ["ceremony","first_dance","dinner"],          mood: { romantic:1.0,elegant:0.9,spiritual:0.1,energetic:0.0,emotional:0.95,joyful:0.3 }, venueTypes: ["hotel_ballroom","outdoor"],                                    religiousLevel:"secular", language:"pt",           era:"50s_60s",        popularity:87 },
  { spotifyId: "7GlBOeep0PBmWZ4JfpSAoZ", name: "Por Você",                artist: "Zezé di Camargo & Luciano",genres: ["sertanejo"],                moments: ["party","dinner"],                           mood: { romantic:0.8,elegant:0.3,spiritual:0.1,energetic:0.6,emotional:0.7,joyful:0.7 }, venueTypes: ["event_hall","private_house"],                                  religiousLevel:"secular", language:"pt",           era:"90s_00s",        popularity:85 },

  // ── FESTA / DANÇA ─────────────────────────────────────────────────────────
  { spotifyId: "3MrRksHupTVEQ7YbA0FsZK", name: "September",               artist: "Earth, Wind & Fire",       genres: ["funk","soul","disco"],       moments: ["party"],                                   mood: { romantic:0.5,elegant:0.4,spiritual:0.0,energetic:0.9,emotional:0.6,joyful:1.0 }, venueTypes: ["event_hall","hotel_ballroom","beach_club"],                    religiousLevel:"secular", language:"en",           era:"70s_80s",        popularity:92 },
  { spotifyId: "7CZyCXKG6d5ALeq41sLzbw", name: "I Will Survive",          artist: "Gloria Gaynor",             genres: ["disco","pop_intl"],          moments: ["party","closing"],                         mood: { romantic:0.3,elegant:0.3,spiritual:0.0,energetic:0.85,emotional:0.6,joyful:0.9 }, venueTypes: ["event_hall","beach_club"],                                     religiousLevel:"secular", language:"en",           era:"70s_80s",        popularity:92 },
  { spotifyId: "2VEZx7NWsZ1D0eJ4uv5Fym", name: "Don't Stop Me Now",      artist: "Queen",                    genres: ["rock"],                      moments: ["party"],                                   mood: { romantic:0.4,elegant:0.3,spiritual:0.0,energetic:1.0,emotional:0.5,joyful:1.0 }, venueTypes: ["event_hall","beach_club"],                                     religiousLevel:"secular", language:"en",           era:"70s_80s",        popularity:95 },
  { spotifyId: "6GOrSmMnP9oLmFFhcrAIFn", name: "Blinding Lights",         artist: "The Weeknd",               genres: ["pop_intl","eletronica"],    moments: ["party"],                                   mood: { romantic:0.7,elegant:0.4,spiritual:0.0,energetic:0.9,emotional:0.7,joyful:0.8 }, venueTypes: ["event_hall","beach_club","rooftop_bar"],                       religiousLevel:"secular", language:"en",           era:"current",        popularity:97 },
  { spotifyId: "6habFhsOp2NvshLv26DqMb", name: "Cheap Thrills",           artist: "Sia",                      genres: ["pop_intl"],                  moments: ["party"],                                   mood: { romantic:0.3,elegant:0.2,spiritual:0.0,energetic:0.85,emotional:0.4,joyful:0.95},  venueTypes: ["event_hall","beach_club"],                                     religiousLevel:"secular", language:"en",           era:"2010s",          popularity:93 },
  { spotifyId: "0s8tEn3QJe0xpMnF9g3Rfl", name: "Então Vai",              artist: "Thiaguinho",               genres: ["pagode","samba_pagode"],     moments: ["party"],                                   mood: { romantic:0.6,elegant:0.2,spiritual:0.0,energetic:0.9,emotional:0.5,joyful:1.0 }, venueTypes: ["event_hall","private_house","beach_club"],                     religiousLevel:"secular", language:"pt",           era:"2010s",          popularity:90 },
  { spotifyId: "1VNMFHyGN6HYAu9TB0yrq7", name: "Jorge de Capadócia",     artist: "Jorge Ben Jor",            genres: ["mpb","samba_pagode"],        moments: ["party","closing"],                         mood: { romantic:0.4,elegant:0.3,spiritual:0.3,energetic:0.8,emotional:0.6,joyful:0.9 }, venueTypes: ["outdoor","event_hall","private_house"],                        religiousLevel:"mixed",   language:"pt",           era:"70s_80s",        popularity:88 },
  { spotifyId: "4fzsfWzRhPawzqhX8Qt9dL", name: "Ai Se Eu Te Pego",        artist: "Michel Teló",              genres: ["sertanejo","pop_br"],       moments: ["party"],                                   mood: { romantic:0.6,elegant:0.1,spiritual:0.0,energetic:0.95,emotional:0.4,joyful:1.0 }, venueTypes: ["event_hall","private_house","beach_club"],                     religiousLevel:"secular", language:"pt",           era:"2010s",          popularity:95 },
  { spotifyId: "27NovPIUIRrOZbo3mKVqJk", name: "Shape of You",            artist: "Ed Sheeran",               genres: ["pop_intl"],                  moments: ["party"],                                   mood: { romantic:0.6,elegant:0.2,spiritual:0.0,energetic:0.85,emotional:0.5,joyful:0.9 }, venueTypes: ["event_hall","beach_club"],                                     religiousLevel:"secular", language:"en",           era:"2010s",          popularity:98 },
  { spotifyId: "5jrdCoLpJSvHHorevXBATy", name: "Uptown Funk",             artist: "Mark Ronson ft. Bruno Mars",genres: ["funk","pop_intl"],          moments: ["party"],                                   mood: { romantic:0.3,elegant:0.3,spiritual:0.0,energetic:0.95,emotional:0.4,joyful:1.0 }, venueTypes: ["event_hall","beach_club"],                                     religiousLevel:"secular", language:"en",           era:"2010s",          popularity:97 },
  { spotifyId: "2NJBLMbXGlLo9PjAl7R3PN", name: "Treasure",               artist: "Bruno Mars",               genres: ["pop_intl","funk"],           moments: ["party"],                                   mood: { romantic:0.7,elegant:0.3,spiritual:0.0,energetic:0.9,emotional:0.5,joyful:0.95}, venueTypes: ["event_hall","beach_club"],                                     religiousLevel:"secular", language:"en",           era:"2010s",          popularity:92 },

  // ── PAGODE / SAMBA (FESTA) ────────────────────────────────────────────────
  { spotifyId: "7wCMN0AwLCvFHRxPP3GYjX", name: "Samba de Uma Nota Só",    artist: "Tom Jobim",                genres: ["samba_pagode","bossa_nova"], moments: ["cocktail","dinner","party"],                mood: { romantic:0.5,elegant:0.6,spiritual:0.0,energetic:0.6,emotional:0.5,joyful:0.8 }, venueTypes: ["event_hall","outdoor","hotel_ballroom"],                       religiousLevel:"secular", language:"pt",           era:"50s_60s",        popularity:85 },
  { spotifyId: "3Y2E8xgz3mzeAVENp6RQJT", name: "Preciso Me Encontrar",   artist: "Cartola",                  genres: ["samba_pagode"],              moments: ["cocktail","dinner"],                        mood: { romantic:0.6,elegant:0.6,spiritual:0.1,energetic:0.4,emotional:0.7,joyful:0.6 }, venueTypes: ["event_hall","outdoor","hotel_ballroom"],                       religiousLevel:"secular", language:"pt",           era:"70s_80s",        popularity:82 },
  { spotifyId: "4RI1iVuATsNQXvMkLiIMRp", name: "No Pagode do Vavá",      artist: "Zeca Pagodinho",           genres: ["samba_pagode"],              moments: ["party"],                                   mood: { romantic:0.3,elegant:0.1,spiritual:0.0,energetic:0.85,emotional:0.4,joyful:1.0 }, venueTypes: ["event_hall","private_house"],                                  religiousLevel:"secular", language:"pt",           era:"90s_00s",        popularity:88 },

  // ── ROCK CLÁSSICO ─────────────────────────────────────────────────────────
  { spotifyId: "6FBPOJLxUZEFT1Mt7muCoW", name: "Bohemian Rhapsody",       artist: "Queen",                    genres: ["rock"],                      moments: ["party","closing"],                         mood: { romantic:0.5,elegant:0.4,spiritual:0.1,energetic:0.8,emotional:0.9,joyful:0.7 }, venueTypes: ["event_hall","beach_club"],                                     religiousLevel:"secular", language:"en",           era:"70s_80s",        popularity:98 },
  { spotifyId: "7tFiyTwD0nx5a1eklYtX2J", name: "Sweet Child O' Mine",    artist: "Guns N' Roses",            genres: ["rock"],                      moments: ["party"],                                   mood: { romantic:0.6,elegant:0.2,spiritual:0.0,energetic:0.9,emotional:0.7,joyful:0.7 }, venueTypes: ["event_hall","beach_club"],                                     religiousLevel:"secular", language:"en",           era:"70s_80s",        popularity:95 },
  { spotifyId: "0WqIKmW4BTrj3eJFmnCKMv", name: "Africa",                 artist: "Toto",                     genres: ["rock","pop_intl"],           moments: ["party"],                                   mood: { romantic:0.5,elegant:0.3,spiritual:0.1,energetic:0.75,emotional:0.6,joyful:0.8 }, venueTypes: ["event_hall"],                                                  religiousLevel:"secular", language:"en",           era:"70s_80s",        popularity:90 },
  { spotifyId: "1TfqLAPs4K3s2rJMoCokcS", name: "Don't Stop Believin'",   artist: "Journey",                  genres: ["rock"],                      moments: ["party","closing"],                         mood: { romantic:0.5,elegant:0.2,spiritual:0.0,energetic:0.85,emotional:0.7,joyful:0.9 }, venueTypes: ["event_hall"],                                                  religiousLevel:"secular", language:"en",           era:"70s_80s",        popularity:93 },

  // ── FORRÓ ─────────────────────────────────────────────────────────────────
  { spotifyId: "2Z8WuEywRWYTKe1NybPnZy", name: "Xote dos Milagres",      artist: "Luiz Gonzaga",             genres: ["forro"],                     moments: ["party"],                                   mood: { romantic:0.5,elegant:0.2,spiritual:0.1,energetic:0.85,emotional:0.5,joyful:0.95}, venueTypes: ["outdoor","private_house","event_hall"],                        religiousLevel:"secular", language:"pt",           era:"50s_60s",        popularity:88 },
  { spotifyId: "3w3y8KPrQkDDl8lMcHHFZP", name: "Paraíba",               artist: "Luiz Gonzaga",             genres: ["forro"],                     moments: ["party"],                                   mood: { romantic:0.4,elegant:0.1,spiritual:0.1,energetic:0.9,emotional:0.6,joyful:1.0 }, venueTypes: ["outdoor","private_house"],                                     religiousLevel:"secular", language:"pt",           era:"50s_60s",        popularity:85 },
  { spotifyId: "6bwMxKM3gHGh89VVRMZ3uW", name: "Esperando na Janela",   artist: "Gilberto Gil",             genres: ["forro","mpb"],               moments: ["cocktail","party"],                         mood: { romantic:0.7,elegant:0.4,spiritual:0.0,energetic:0.6,emotional:0.6,joyful:0.8 }, venueTypes: ["outdoor","event_hall"],                                        religiousLevel:"secular", language:"pt",           era:"70s_80s",        popularity:85 },

  // ── ENCERRAMENTO ─────────────────────────────────────────────────────────
  { spotifyId: "4LRPiXqCikLlN15c3yImP7", name: "What a Wonderful World", artist: "Louis Armstrong",          genres: ["jazz","pop_intl"],           moments: ["closing"],                                 mood: { romantic:0.6,elegant:0.7,spiritual:0.3,energetic:0.1,emotional:0.9,joyful:0.8 }, venueTypes: ["outdoor","event_hall","hotel_ballroom"],                       religiousLevel:"secular", language:"en",           era:"50s_60s",        popularity:95 },
  { spotifyId: "7MXVkk9YMctZqd1Srtv4MB", name: "Angels",                artist: "Robbie Williams",          genres: ["pop_intl"],                  moments: ["closing"],                                 mood: { romantic:0.7,elegant:0.5,spiritual:0.4,energetic:0.2,emotional:0.95,joyful:0.5 }, venueTypes: ["event_hall","outdoor"],                                        religiousLevel:"mixed",   language:"en",           era:"90s_00s",        popularity:90 },
  { spotifyId: "0ET7LF7PJBIZ96WNpG8ioP", name: "Minha Vida",            artist: "Paula Fernandes",          genres: ["sertanejo","pop_br"],        moments: ["closing"],                                 mood: { romantic:0.8,elegant:0.4,spiritual:0.3,energetic:0.2,emotional:0.95,joyful:0.4 }, venueTypes: ["event_hall","private_house"],                                  religiousLevel:"mixed",   language:"pt",           era:"2010s",          popularity:85 },
  { spotifyId: "5fNL8oQ4l2YMCFmZFONBkd", name: "Time of My Life",       artist: "Bill Medley & Jennifer Warnes", genres: ["pop_intl"],             moments: ["closing","party"],                         mood: { romantic:0.8,elegant:0.4,spiritual:0.0,energetic:0.7,emotional:0.85,joyful:0.8 }, venueTypes: ["event_hall"],                                                  religiousLevel:"secular", language:"en",           era:"70s_80s",        popularity:90 },
  { spotifyId: "6Z81V1FiqUuFAbfCgiQR5U", name: "Emoções",               artist: "Roberto Carlos",           genres: ["mpb","pop_br"],              moments: ["closing"],                                 mood: { romantic:0.8,elegant:0.5,spiritual:0.2,energetic:0.2,emotional:1.0,joyful:0.5 }, venueTypes: ["event_hall","hotel_ballroom"],                                 religiousLevel:"secular", language:"pt",           era:"70s_80s",        popularity:90 },

  // ── 15 ANOS (ESPECÍFICO) ─────────────────────────────────────────────────
  { spotifyId: "2LlQb7Uoj1kKyGhlkBf9aC", name: "Meu Maior Presente",     artist: "Zezé di Camargo & Luciano",genres: ["sertanejo"],                moments: ["entrance","first_dance"],                  mood: { romantic:0.6,elegant:0.5,spiritual:0.3,energetic:0.2,emotional:1.0,joyful:0.5 }, venueTypes: ["event_hall","hotel_ballroom"],                                 religiousLevel:"secular", language:"pt",           era:"90s_00s",        popularity:85 },
  { spotifyId: "2Weg0thPnI1mTVNkzOqjk6", name: "Clichê Teen",           artist: "Fresno",                   genres: ["rock","pop_br"],             moments: ["party"],                                   mood: { romantic:0.5,elegant:0.1,spiritual:0.0,energetic:0.9,emotional:0.6,joyful:0.9 }, venueTypes: ["event_hall"],                                                  religiousLevel:"secular", language:"pt",           era:"2010s",          popularity:82 },
  { spotifyId: "1cNf5WAMEvXCdKNpMsHBKF", name: "As Time Goes By",       artist: "Dooley Wilson",            genres: ["jazz","pop_intl"],           moments: ["waltz","ceremony"],                         mood: { romantic:0.9,elegant:0.9,spiritual:0.0,energetic:0.1,emotional:0.9,joyful:0.3 }, venueTypes: ["hotel_ballroom","historic_venue"],                             religiousLevel:"secular", language:"en",           era:"50s_60s",        popularity:82 },

  // ── CORPORATIVO ──────────────────────────────────────────────────────────
  { spotifyId: "6uY4MKN0VWGH0nqGYWxOGk", name: "Also Sprach Zarathustra",artist: "Richard Strauss",          genres: ["classical"],                 moments: ["event_opening"],                           mood: { romantic:0.1,elegant:0.9,spiritual:0.2,energetic:0.8,emotional:0.7,joyful:0.4 }, venueTypes: ["hotel_ballroom","event_hall"],                                 religiousLevel:"secular", language:"instrumental", era:"classic_timeless", popularity:88 },
  { spotifyId: "3J0MbPBFaT4AH7WVVGi4xQ", name: "Smooth Operator",       artist: "Sade",                     genres: ["jazz","lounge"],             moments: ["networking","cocktail","dinner"],           mood: { romantic:0.7,elegant:0.9,spiritual:0.0,energetic:0.2,emotional:0.5,joyful:0.4 }, venueTypes: ["hotel_ballroom","rooftop_bar"],                                religiousLevel:"secular", language:"en",           era:"70s_80s",        popularity:90 },
  { spotifyId: "0diAoCFvfCxM9Gg4KCf3Jr", name: "Ain't No Mountain High Enough", artist: "Marvin Gaye",       genres: ["soul","pop_intl"],           moments: ["event_opening","party"],                   mood: { romantic:0.6,elegant:0.5,spiritual:0.1,energetic:0.8,emotional:0.7,joyful:0.9 }, venueTypes: ["hotel_ballroom","event_hall"],                                 religiousLevel:"secular", language:"en",           era:"50s_60s",        popularity:90 },
];

async function main() {
  console.log("🌱 Iniciando seed do banco de músicas curadas...");

  let created = 0;
  let updated = 0;

  for (const track of curatedTracks) {
    const result = await prisma.curatedTrack.upsert({
      where:  { spotifyId: track.spotifyId },
      update: {
        name:            track.name,
        artist:          track.artist,
        genres:          track.genres,
        moments:         track.moments,
        mood:            track.mood,
        venueTypes:      track.venueTypes,
        religiousLevel:  track.religiousLevel,
        language:        track.language,
        era:             track.era,
        popularity:      track.popularity,
        curatorApproved: true,
        durationMs:      track.durationMs ?? 200000,
      },
      create: {
        spotifyId:       track.spotifyId,
        name:            track.name,
        artist:          track.artist,
        genres:          track.genres,
        moments:         track.moments,
        mood:            track.mood,
        venueTypes:      track.venueTypes,
        religiousLevel:  track.religiousLevel,
        language:        track.language,
        era:             track.era,
        popularity:      track.popularity,
        curatorApproved: true,
        durationMs:      track.durationMs ?? 200000,
      },
    });

    if (result) {
      const isNew = result.createdAt.getTime() === result.updatedAt.getTime();
      isNew ? created++ : updated++;
    }
  }

  console.log(`✅ Seed concluído! ${created} criadas, ${updated} atualizadas.`);
  console.log(`   Total no banco: ${curatedTracks.length} músicas curadas.`);
}

main()
  .catch((e) => {
    console.error("❌ Erro no seed:", e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
